export default [
  { emoji: '🇦🇨', ru: 'о-в Вознесения', en: 'Ascension Island' },
  { emoji: '🇦🇩', ru: 'Андорра', en: 'Andorra' },
  { emoji: '🇦🇪', ru: 'ОАЭ', en: 'United Arab Emirates' },
  { emoji: '🇦🇫', ru: 'Афганистан', en: 'Afghanistan' },
  { emoji: '🇦🇬', ru: 'Антигуа и Барбуда', en: 'Antigua & Barbuda' },
  { emoji: '🇦🇮', ru: 'Ангилья', en: 'Anguilla' },
  { emoji: '🇦🇱', ru: 'Албания', en: 'Albania' },
  { emoji: '🇦🇲', ru: 'Армения', en: 'Armenia' },
  { emoji: '🇦🇴', ru: 'Ангола', en: 'Angola' },
  { emoji: '🇦🇶', ru: 'Антарктида', en: 'Antarctica' },
  { emoji: '🇦🇷', ru: 'Аргентина', en: 'Argentina' },
  { emoji: '🇦🇸', ru: 'Американское Самоа', en: 'American Samoa' },
  { emoji: '🇦🇹', ru: 'Австрия', en: 'Austria' },
  { emoji: '🇦🇺', ru: 'Австралия', en: 'Australia' },
  { emoji: '🇦🇼', ru: 'Аруба', en: 'Aruba' },
  { emoji: '🇦🇽', ru: 'Аландские о-ва', en: 'Åland Islands' },
  { emoji: '🇦🇿', ru: 'Азербайджан', en: 'Azerbaijan' },
  { emoji: '🇧🇦', ru: 'Босния и Герцеговина', en: 'Bosnia & Herzegovina' },
  { emoji: '🇧🇧', ru: 'Барбадос', en: 'Barbados' },
  { emoji: '🇧🇩', ru: 'Бангладеш', en: 'Bangladesh' },
  { emoji: '🇧🇪', ru: 'Бельгия', en: 'Belgium' },
];
