export default [
  { emoji: '🍇', ru: 'Виноград', en: 'grapes' },
  { emoji: '🍈', ru: 'Дыня', en: 'melon' },
  { emoji: '🍉', ru: 'Арбуз', en: 'watermelon' },
  { emoji: '🍊', ru: 'Мандарин', en: 'tangerine' },
  { emoji: '🍋', ru: 'Лемон', en: 'lemon' },
  { emoji: '🍌', ru: 'Банан', en: 'banana' },
  { emoji: '🍍', ru: 'Ананас', en: 'pineapple' },
  { emoji: '🥭', ru: 'Манго', en: 'mango' },
  { emoji: '🍎', ru: 'Яблоко', en: 'apple' },
  { emoji: '🍐', ru: 'Груша', en: 'pear' },
  { emoji: '🍑', ru: 'Персик', en: 'peach' },
  { emoji: '🍒', ru: 'Вишня', en: 'cherry' },
  { emoji: '🍓', ru: 'Клубника', en: 'strawberry' },
  { emoji: '🥝', ru: 'Киви', en: 'kiwi' },
  { emoji: '🍅', ru: 'Помидор', en: 'tomato' },
  { emoji: '🥥', ru: 'Кокос', en: 'coconut' },
  { emoji: '🥑', ru: 'Авокадо', en: 'avocado' },
  { emoji: '🍆', ru: 'Баклажан', en: 'eggplant' },
  { emoji: '🥔', ru: 'Картофель', en: 'potato' },
  { emoji: '🥕', ru: 'Морковь', en: 'carrot' },
  { emoji: '🌽', ru: 'Кукуруза', en: 'corn' },
  { emoji: '🌶', ru: 'Перец', en: 'pepper' },
  { emoji: '🥒', ru: 'Огурец', en: 'cucumber' },
  { emoji: '🥬', ru: 'Салат', en: 'salad' },
  { emoji: '🥦', ru: 'Броколли', en: 'broccoli' },
  // TODO 🥜, 🌰?
];
