export default [
  { emoji: '👨‍⚕', ru: 'Доктор', en: 'doctor' },
  { emoji: '👨‍🎓', ru: 'Студент', en: 'student' },
  { emoji: '👩‍🏫', ru: 'Учитель', en: 'teacher' },
  { emoji: '👩‍⚖', ru: 'Судья', en: 'judge' },
  { emoji: '👨‍🌾', ru: 'Фермер', en: 'farmer' },
  { emoji: '👩‍🍳', ru: 'Повар', en: 'chef' },
  { emoji: '👨‍🔧', ru: 'Электрик', en: 'electrician' },
  { emoji: '👨‍🏭', ru: 'Рабочий', en: 'worker' },
  { emoji: '👩‍💼', ru: 'Менеджер', en: 'manager' },
  { emoji: '👨‍🔬', ru: 'Ученый', en: 'scientist' },
  { emoji: '👨‍💻', ru: 'Разработчик', en: 'developer' },
  { emoji: '👨‍🎨', ru: 'Художник', en: 'artist' },
  { emoji: '👨‍✈', ru: 'Пилот', en: 'pilot' },
  { emoji: '👩‍🚀', ru: 'Космонавт', en: 'astronaut' },
  { emoji: '👨‍🚒', ru: 'Пожарный', en: 'firefighter' },
  { emoji: '👮‍♂', ru: 'Полицейский', en: 'cop' },
  { emoji: '🕵‍♂', ru: 'Детектив', en: 'detective' },
];
